### PR TITLE
Potree v2 support

### PR DESCRIPTION
**Pull request by cognitivedata**
It works! 

This fork provides (evolving) support for Potree v2 file format to the [BA_PointCloud](https://github.com/SFraissTU/BA_PointCloud) Unity implementation.

As of 20230216 loading Potree v2 from local storage works, but loading from a server (with http queries) does not, yet.

Due to the Potree documentation being [missing in action](https://github.com/potree/potree/commit/a41aae95d32fbee43e21ad4a38e1b1d2b2386210), i had to rely on [
PotreeDesktop](https://github.com/potree/PotreeDesktop) JS/TS implementation. Therefore, there shall be bugs!

Speaking of which: if you come across those, please do report. Or even better: squash and pull.

### CODE REVIEW

**Comment by SFraissTU** [comment]
Thanks a lot for your work! I plan to review it next week!

**Comment by chris-traxler** [comment]
Good to see, that support for v2 is under development. We would also need it for one of our projects at VRVis.
@SFraissTU : What is the plan for this pull request? Can you estimate when it will be reviewed? We are also very interested that it works for WebGL builds. Maybe we have the resources to contribute, but I cannot promise yet.

**Comment by SFraissTU** [comment]
@chris-traxler: I've already looked at it and fixed some issues with it. There are still some final things I want to improve before merging it. I will take a look at it at the weekend again and plan to give an update afterwards.

**Comment by chris-traxler** [comment]
@SFraissTU: Great, thanks for the information 🙂

**Comment by SFraissTU** [comment]
The branch is merged.
See branch potreev2 for the changes that I applied to the original pull request: https://github.com/SFraissTU/BA_PointCloud/commits/potreev2
Some changes fixed serious issues, others are more cosmetic.  I've also added V2-support for previously unsupported features such as previewing, translation to center etc.

**Pull request merged**
